ci: check for Swagger Codegen Changes
Check for uncommitted Swagger Codegen changes through dependencies, updates, etc.

diff --git a/.github/workflows/jobs.yaml b/.github/workflows/jobs.yaml
--- a/.github/workflows/jobs.yaml
+++ b/.github/workflows/jobs.yaml
@@ -110,8 +110,60 @@ jobs:
         run: |
           ./check-deadcode.sh
 
+  swagger-codegen:
+    name: "Check for uncommitted changes through Swagger Codegen Changes."
+    needs:
+      - lint-job
+      - ui-assets
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        go-version: [1.24.x]
+        os: [ubuntu-latest]
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v5
+      - name: Set up Go ${{ matrix.go-version }} on ${{ matrix.os }}
+        uses: actions/setup-go@v6
+        with:
+          go-version: ${{ matrix.go-version }}
+      - name: Read .nvmrc
+        id: node_version
+        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
+      - name: Enable Corepack
+        run: corepack enable
+      - name: Setup Node
+        uses: actions/setup-node@v5
+        with:
+          node-version: ${{ env.NVMRC }}
+          cache: "yarn"
+          cache-dependency-path: web-app/yarn.lock
+      - name: Install NPM Dependencies
+        working-directory: ./web-app
+        continue-on-error: false
+        run: |
+          yarn install --immutable
+
+      - name: Run Swagger Codegen
+        run: make swagger-gen
+
+      - name: Check for uncommitted changes
+        id: git-status
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "::error::Codegen modified files. Please run "make swagger-gen" and commit the changes:"
+            git status --porcelain
+            echo "##### Git Diff: #####"
+            git --no-pager diff
+            exit 1
+          else
+            echo "No changes detected after codegen."
+          fi
+
   latest-minio:
     name: Test Build latest MinIO with Console
+    needs:
+      - swagger-codegen
     runs-on: [ubuntu-latest]
     strategy:
       matrix:
@@ -192,6 +244,7 @@ jobs:
       - lint-job
       - ui-assets
       - semgrep-static-code-analysis
+      - swagger-codegen
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
